# Generated by Django 5.1.4 on 2024-12-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_transaction_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_type',
            new_name='pay_type',
        ),
    ]
