# Generated by Django 5.1.4 on 2024-12-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('house_number', models.CharField(max_length=10)),
                ('zone', models.IntegerField()),
            ],
        ),
    ]
