# Generated by Django 5.1.4 on 2024-12-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.IntegerField()),
                ('model', models.CharField(max_length=10)),
                ('make', models.CharField(max_length=10)),
            ],
        ),
    ]
