# Generated by Django 5.1.4 on 2024-12-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('id_number', models.IntegerField()),
                ('vehicle_number', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
